### ISSUE TITLE
Ip, user and password

### ISSUE THREAD

**Issue by gabryk91** [BrettSheleski/SmartThingsPublic#14]
Hi, I'm uncertain about where to get those info.
Ip is the sonoff ip address in my local network? Like 192.168.0.X?
Where I can find user and password? Are those set in the "Configure MQTT" section of the sonoff webserver?

I had followed the instruction and added the device handler and the device, but my app can't connect to it. Also, in the Tasmota-Power type device what I should enter in "Power channel" field?
Thanks

**Comment by BrettSheleski** [comment]
You'll need to add both the `Tasmota` and `Tasmota-Power` device handlers in the SmartThings IDE.

When adding your device, just add a single `Tasmota` device and set the IP address to the local IP address of your Sonoff device (yes, your 192.168.0.X value).  If you configured the Sonoff to require a username and password, set it there as well (this has nothing to do with MQTT settings).  If you're able to connect to the web interface of your Sonoff without using a username/password, then the username/password fields should be left blank.

Do not manually add any `Tasmota-Power` devices, that will happen automatically (see below).

What should happen when the device is installed, it makes a request to the Sonoff device to determine the module type (Sonoff Basic, Sonoff 4CH, etc.).  After figuring out the module type, the device will create child devices accordingly.  For a Sonoff-Basic module, it will create a single child device using the `Tasmota-Power` device handler.  For Sonoff 4CH modules, it creates 4 `Tasmota-Power` child devices.  The `Power Channel` field will get set appropriately for each child device and is not intended to need to be set manually.

**Comment by gabryk91** [comment]
First, thanks for the exaustive answer, I did almost everything correctly but I think I was too impatient: I guess that it can take a while to create the devices, right? Because i added the 2 handlers but then I added the device myself

**Comment by BrettSheleski** [comment]
It should be pretty immediate to create the child device(s).  You should see the child device(s) as just another device in your SmartThings app after installing the `Tasmota` device.

**Comment by gabryk91** [comment]
Ok, I've a problem then: the tasmota-power device isn't created. From the app I can see the changes I made through the web portal, so they are seeing each other.
One though: it is possible that my router is blocking the connection to the sonoff? What port does it use to connect to the smartthing web page? Because I can't figure how, from the cloud, it can connect to a local ip in my private network.
Also: is the samsung hub required? Thanks

**Comment by BrettSheleski** [comment]
"Also: is the samsung hub required?"

If you mean the SmartThings hub, then yes.  Having a SmartThings hub is definitely required.

**Comment by gabryk91** [comment]
d'oh... is there another way to use tasmota sonoff with google home?
