### ISSUE TITLE
Sonoff POW

### ISSUE THREAD

**Issue by hshir** [BrettSheleski/SmartThingsPublic#16]
Hi there
I have installed this device handler using POW sonoff, unfotunately, nothing is working, its all blanks and refresh doesn't do anything.
Is this suppose to work with POW 

Thx
Hillel

**Comment by BrettSheleski** [comment]
I have not yet testing with the Sonoff POW, however it should have basic functionality.  I would like to implement the Power Meter capability (see http://docs.smartthings.com/en/latest/capabilities-reference.html#power-meter) for this module type, but have not implemented it yet.

Can you provide screenshots of your setup?

**Comment by jaysuk** [comment]
I would be interested in the position meter capability.
I can confirm that your code gives basic functionality. 

I would be happy to test any changes you make

**Comment by BrettSheleski** [comment]
I do actually have one of these devices, just have yet to actually use it, much less make a SmartThings Device Handler for it.

Since this is mainly a monitor of power whose status should automatically be updated, it will need to rely on the SmartApp, and a way of communicating to the SmartApp.  One way of doing so would be to use Node-Red.

**Comment by jaysuk** [comment]
I already use node-red to monitor the current and do something with it.
I was just hoping to start to migrate my home automation to smartthings

**Comment by BrettSheleski** [comment]
I too would prefer everything in SmartThings, but until the Tasmota firmware updates SmartThings directly, we'll need a little help from something.

Node-Red works for my needs.

There's also a SmartThings to MQTT bridge project on GitHub [here](https://github.com/stjohnjohnson/smartthings-mqtt-bridge). You may also be able to use it in some way. Perhaps that project could be forced to specifically target Tasmota devices and device handlers.

**Comment by hshir** [comment]
Hi there

Any new regarding the power reading in ST?

Thx
Hillel

**Comment by BrettSheleski** [comment]
Nope
