### ISSUE TITLE
Sonoff Devices Working

### ISSUE THREAD

**Issue by jaysuk** [BrettSheleski/SmartThingsPublic#18]
Topic to discuss which devices have been tested and confirmed working.
Please include sonoff type and whats working

**Comment by jaysuk** [comment]
Sonoff POW - basic functionality only.
Sonoff S20 - on/off
Sonoff BN-SZ01 - on/off only - can't control brightness
Sonoff LED - on/off only - can't control brightness or warm/cold

**Comment by BrettSheleski** [comment]
Please make an issue for each one of these devices instead of one huge one.

Also, since this device handler relies on the Tasmpta http commands, it would be helpful if you could determine which commands to use for the desired functionality.
